# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Github Buddhist University
author: Ven Khemarato
email: khemarato.bhikkhu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A Github-hosted website dedicated to providing free,
  online courses in Buddhist Studies. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://buddhist-uni.github.io" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-159403467-1
github_username:  buddhist-uni
header_pages: [courses.md, library.md, blog.md, about.md]

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
rss: atom
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

permalink: pretty

collections:
  authors:
     output: true
     permalink: /:collection/:name
  content:
     output: true
     permalink: /:collection/:path
  courses:
     output: true
     permalink: /:collection/:name
  tags:
     output: true
     permalink: /:collection/:name
  posts:
     output: true
     permalink: blog/:year/:month/:day/:title

defaults:
  -
    scope:
        path: ""
    values:
        layout: "page"
  -
    scope:
        path: ""
        type: "posts"
    values:
        layout: "post"
  - 
    scope:
        path: ""
        type: "courses"
    values:
        layout: "course"
  - 
    scope:
        path: ""
        type: "authors"
    values:
        layout: "author"
  - 
    scope:
        path: ""
        type: "tags"
    values:
        layout: "tag"
  -
    scope:
        path: ""
        type: "content"
    values:
        formats: [pdf, epub]
        layout: "content"
  -
    scope:
        path: "content"
        type: "pages"
    values:
        layout: "content-category"
  -
    scope:
        path: "_content/av"
        type: "content"
    values:
        formats: [mp3]
