BLACKLISTED_DOMAINS: !!set
  accesstoinsight.org: null
  archive.is: null
  archive.org: null
  caitlinjohnstone.com: null
  daily.readingfaithfully.org: null
  darrennaish.files.wordpress.com: null
  discourse.suttacentral.net: null
  greatergood.berkeley.edu: null
  harpers.org: null
  hbr.org: null
  jacobinmag.com: null
  lareviewofbooks.org: null
  logicmag.io: null
  matthewremski.medium.com: null
  plato.stanford.edu: null
  plumvillage.org: null
  present.bhikkhuni.net: null
  punctumbooks.com: null
  sc.readingfaithfully.org: null
  seop.illc.uva.nl: null
  sinoindian.wordpress.com: null
  strikemag.org: null
  studybuddhism.com: null
  suttacentral.net: null
  suttafriends.org: null
  teahouse.buddhistdoor.net: null
  thefearlessheart.org: null
  tricycle.org: null
  www.aa.com.tr: null
  www.accesstoinsight.org: null
  www.bhikkhuni.net: null
  www.denverpost.com: null
  www.dissentmagazine.org: null
  www.guernicamag.com: null
  www.huffpost.com: null
  www.insidehighered.com: null
  www.lionsroar.com: null
  www.newyorker.com: null
  www.noahpinion.blog: null
  www.nybooks.com: null
  www.paliaudio.com: null
  www.poetryfoundation.org: null
  www.readingfaithfully.org: null
  www.suttas.net: null
  www.texasobserver.org: null
  www.theatlantic.com: null
  www.theguardian.com: null
  www.theverge.com: null
  www.vice.com: null
  www.vox.com: null
  www.wired.com: null
  wwzc.org: null
WHITELISTED_DOMAINS: !!set
  2012books.lardbucket.org: null
  academic.oup.com: null
  amaravati.org: null
  ancient-buddhist-texts.net: null
  api.equinoxpub.com: null
  archive.boston.com: null
  arrowriver.ca: null
  bdkamerica.org: null
  bhantesuddhaso.com: null
  bhikkhucintita.wordpress.com: null
  bit.ly: null
  blogs.dickinson.edu: null
  bps.lk: null
  bschawaii.org: null
  bswa.org: null
  budblooms.org: null
  ci.nii.ac.jp: null
  deepblue.lib.umich.edu: null
  dharmaebooks.org: null
  dictionary.sutta.org: null
  digitalcommons.linfield.edu: null
  direct.mit.edu: null
  doi.org: null
  drexel.edu: null
  dukelibraries.contentdm.oclc.org: null
  dx.doi.org: null
  forestdhamma.org: null
  forestsangha.org: null
  ftp.budaedu.org: null
  hal.science: null
  hdl.handle.net: null
  hub.hku.hk: null
  icabs.repo.nii.ac.jp: null
  id.nii.ac.jp: null
  ijkh.khistory.org: null
  internationaljournaldharmastudies.springeropen.com: null
  issuu.com: null
  jocbs.org: null
  journal.equinoxpub.com: null
  journals.lww.com: null
  journals.plos.org: null
  journals.ub.uni-heidelberg.de: null
  lapislazulitexts.com: null
  library.achievingthedream.org: null
  library.oapen.org: null
  link.springer.com: null
  media.amaravati.org: null
  medium.com: null
  name.readingfaithfully.org: null
  nap.nationalacademies.org: null
  newprairiepress.org: null
  nirc.nanzan-u.ac.jp: null
  oer.galileo.usg.edu: null
  onlinelibrary.wiley.com: null
  open.lib.umn.edu: null
  open.maricopa.edu: null
  openstax.org: null
  opentextbc.ca: null
  otani.repo.nii.ac.jp: null
  papers.ssrn.com: null
  pdx.pressbooks.pub: null
  ped.readingfaithfully.org: null
  philosophyreligion.wordpress.com: null
  poj.peeters-leuven.be: null
  press.rebus.community: null
  pressbooks.bccampus.ca: null
  pressbooks.oer.hawaii.edu: null
  quod.lib.umich.edu: null
  read.84000.co: null
  readingfaithfully.org: null
  santifm.org: null
  scholarlypublications.universiteitleiden.nl: null
  seeingthroughthenet.net: null
  shardarogell.com: null
  sirimangalo.org: null
  socialsci.libretexts.org: null
  ssrn.com: null
  standardebooks.org: null
  static.sirimangalo.org: null
  store.pariyatti.org: null
  theanarchistlibrary.org: null
  thecjbs.org: null
  thubtenchodron.org: null
  uva.theopenscholar.com: null
  web.archive.org: null
  wiswo.org: null
  www.108wisdom.org: null
  www.abhayagiri.org: null
  www.ajahnchah.org: null
  www.ancient-buddhist-texts.net: null
  www.are.na: null
  www.aupress.ca: null
  www.bps.lk: null
  www.buddhanet.net: null
  www.buddhistelibrary.org: null
  www.buddhistische-gesellschaft-berlin.de: null
  www.degruyter.com: null
  www.dhammatalks.org: null
  www.dhammathai.org: null
  www.dharmasite.net: null
  www.frontiersin.org: null
  www.globalbuddhism.org: null
  www.gutenberg.org: null
  www.jocbs.org: null
  www.jstor.org: null
  www.kammatthana.com: null
  www.kbrl.gov.mm: null
  www.lotsawahouse.org: null
  www.mediafire.com: null
  www.metmuseum.org: null
  www.ncbi.nlm.nih.gov: null
  www.opendemocracy.net: null
  www.researchgate.net: null
  www.scribd.com: null
  www.sheldrake.org: null
  www.shengyen.org: null
  www.shin-ibs.edu: null
  www.sirimangalo.org: null
  www.suanmokkh.org: null
  www.taylorfrancis.com: null
  www.ucpress.edu: null
  www.un.org: null
  www.watpahnanachat.org: null
  www.yorku.ca: null
  www.youtube.com: null
  www.zakstein.org: null
  youtu.be: null
  youtube.com: null
