BLACKLISTED_DOMAINS: !!set
  accesstoinsight.org: null
  archive.is: null
  archive.org: null
  caitlinjohnstone.com: null
  daily.readingfaithfully.org: null
  darrennaish.files.wordpress.com: null
  discourse.suttacentral.net: null
  doi.org: null
  greatergood.berkeley.edu: null
  harpers.org: null
  hbr.org: null
  jacobinmag.com: null
  lareviewofbooks.org: null
  logicmag.io: null
  matthewremski.medium.com: null
  plato.stanford.edu: null
  plumvillage.org: null
  pluralism.org: null
  present.bhikkhuni.net: null
  punctumbooks.com: null
  sc.readingfaithfully.org: null
  seop.illc.uva.nl: null
  sinoindian.wordpress.com: null
  stonerecords.co.uk: null
  store.pariyatti.org: null
  strikemag.org: null
  studybuddhism.com: null
  suttacentral.net: null
  suttafriends.org: null
  teahouse.buddhistdoor.net: null
  thefearlessheart.org: null
  tricycle.org: null
  web.archive.org: null
  www.aa.com.tr: null
  www.accesstoinsight.org: null
  www.bhikkhuni.net: null
  www.denverpost.com: null
  www.dissentmagazine.org: null
  www.guernicamag.com: null
  www.huffpost.com: null
  www.insidehighered.com: null
  www.lionsroar.com: null
  www.newyorker.com: null
  www.noahpinion.blog: null
  www.nybooks.com: null
  www.paliaudio.com: null
  www.poetryfoundation.org: null
  www.readingfaithfully.org: null
  www.suttas.net: null
  www.texasobserver.org: null
  www.theatlantic.com: null
  www.theguardian.com: null
  www.theverge.com: null
  www.vice.com: null
  www.vox.com: null
  www.wired.com: null
  wwzc.org: null
REDIRECT_PDFS: !!set
  /content/articles/early-development-of-buddhist-literature_cousins: null
  /content/articles/engaged-buddhism_gleig-ann: null
  /content/articles/engaged-buddhism_temprano-victor: null
  /content/articles/epistemology-of-the-brahmajala-sutta_stephen-a-evans: null
  /content/articles/how-gnosis-met-logos-story-of_deleanu-f: null
  /content/articles/sal-an-alternative-buddhist-holy-tree_ireland: null
  /content/articles/three-turnings_powers-john: null
  /content/articles/to-be-or-not-to-be_gessen-masha: null
  /content/booklets/buddhist-cosmos_punnadhammo: null
  /content/booklets/ecocrisis-perspectives: null
  /content/booklets/facing-the-future_bodhi: null
  /content/booklets/footprints-in-the-dust_dhammika: null
  /content/booklets/in-his-own-words_nyanamoli: null
  /content/booklets/kalama-sutta-free-inquiry_soma-thera: null
  /content/booklets/mindfulness_sumedho: null
  /content/booklets/noble-strategy_geoff: null
  /content/booklets/rebirth-explained_gunaratna: null
  /content/booklets/refuge_geoff: null
  /content/booklets/role-of-animals-in-indian-buddhism-with_diem-nguyen-thi: null
  /content/booklets/sn-anthology_ireland: null
  /content/booklets/sn-anthology_walshe: null
  /content/booklets/the-discourse-on-right-view_nyanamoli: null
  /content/booklets/thirty-seven-practices-of-a-bodhisattva: null
  /content/booklets/this-is-the-path_dtun-t: null
  /content/canon/bodhisattvamanyavali_atisha: null
  /content/canon/book-of-the-discipline_horner: null
  /content/canon/dn22: null
  /content/canon/jataka-gatha-vannana: null
  /content/canon/nidanakatha: null
  /content/canon/patthana.paccayuddesaniddesa: null
  /content/canon/t1586: null
  /content/essays/abhidharma-praise_rongton: null
  /content/essays/advice-to-gok-zangden_gangshar: null
  /content/essays/beauty-of-sila_jayasaro: null
  /content/essays/bodhicaryavatara-overview_zenkar: null
  /content/essays/bringing-sickness-onto-the-path_changchup: null
  /content/essays/buddha-you-never-knew_dhammika: null
  /content/essays/karma-vibanga-reliefs-at-borobudur_anandajoti: null
  /content/essays/naturally-liberating-whatever_gangshat: null
  /content/essays/sankassa_dhammika: null
  /content/essays/trekcho_mipham: null
  /content/monographs/life-of-the-buddha_nyanamoli: null
  /content/monographs/lost-kingdoms-hindu-buddhist-sculpture_guy-john: null
  /content/monographs/metaphor-and-literalism_hwang-soonil: null
  /content/monographs/miracle-of-mindfulness_tnh: null
  /content/monographs/poetry-of-meng-haoran_kroll-paul: null
  /content/monographs/similes-of-the-buddha_hecker: null
  /content/monographs/what-the-buddha-taught_rahula-w: null
  /content/reference/concise-pali-dictionary: null
  /content/reference/pali-name-index: null
SEARCHABLE_PDFS: !!set
  /content/articles/early-buddhism-and-urban-revolution_gokhale: null
  /content/articles/light-emitting-image-of-magadha-in-tang_wong-dorothy: null
  /content/articles/origin-of-pali_norman: null
  /content/articles/putting-smrti-back-into-sati-putting_levman-bryan: null
  /content/articles/tantra_gray-david: null
  /content/booklets/against-the-defilements_suchart: null
  /content/booklets/arahattamagga-arahattaphala_mahabua: null
  /content/booklets/buddha-and-his-dhamma_bodhi: null
  /content/booklets/chinese-liturgy_stc: null
  /content/booklets/gifts-he-left-behind_dun: null
  /content/booklets/how-to-meditate_yuttadhammo: null
  /content/booklets/htm2_yuttadhammo: null
  /content/booklets/mn-selections_nyanamoli-bodhi: null
  /content/booklets/satipatthana-vipassana_mahasi: null
  /content/booklets/thai-chanting_anandajoti: null
  /content/essays/mind-and-its-endless-rebirth_suchart: null
  /content/monographs/nature-in-ebts_dhammika: null
WHITELISTED_DOMAINS: !!set
  2012books.lardbucket.org: null
  academic.oup.com: null
  amaravati.org: null
  ancient-buddhist-texts.net: null
  api.equinoxpub.com: null
  archive.boston.com: null
  arrowriver.ca: null
  bdkamerica.org: null
  bhantesuddhaso.com: null
  bhikkhucintita.wordpress.com: null
  bit.ly: null
  blogs.dickinson.edu: null
  bps.lk: null
  bschawaii.org: null
  bswa.org: null
  budblooms.org: null
  ci.nii.ac.jp: null
  deepblue.lib.umich.edu: null
  dharmaebooks.org: null
  dictionary.sutta.org: null
  digitalcommons.linfield.edu: null
  direct.mit.edu: null
  drexel.edu: null
  dukelibraries.contentdm.oclc.org: null
  dx.doi.org: null
  forestdhamma.org: null
  forestsangha.org: null
  ftp.budaedu.org: null
  hal.science: null
  hdl.handle.net: null
  hub.hku.hk: null
  icabs.repo.nii.ac.jp: null
  id.nii.ac.jp: null
  ijkh.khistory.org: null
  internationaljournaldharmastudies.springeropen.com: null
  issuu.com: null
  jocbs.org: null
  journal.equinoxpub.com: null
  journals.lww.com: null
  journals.plos.org: null
  journals.ub.uni-heidelberg.de: null
  lapislazulitexts.com: null
  library.achievingthedream.org: null
  library.oapen.org: null
  link.springer.com: null
  media.amaravati.org: null
  medium.com: null
  name.readingfaithfully.org: null
  nap.nationalacademies.org: null
  newprairiepress.org: null
  nirc.nanzan-u.ac.jp: null
  oer.galileo.usg.edu: null
  onlinelibrary.wiley.com: null
  open.lib.umn.edu: null
  open.maricopa.edu: null
  openstax.org: null
  opentextbc.ca: null
  otani.repo.nii.ac.jp: null
  papers.ssrn.com: null
  pdx.pressbooks.pub: null
  ped.readingfaithfully.org: null
  philosophyreligion.wordpress.com: null
  poj.peeters-leuven.be: null
  press.rebus.community: null
  pressbooks.bccampus.ca: null
  pressbooks.oer.hawaii.edu: null
  quod.lib.umich.edu: null
  read.84000.co: null
  readingfaithfully.org: null
  santifm.org: null
  scholarlypublications.universiteitleiden.nl: null
  seeingthroughthenet.net: null
  shardarogell.com: null
  shodhganga.inflibnet.ac.in: null
  sirimangalo.org: null
  socialsci.libretexts.org: null
  ssrn.com: null
  standardebooks.org: null
  static.sirimangalo.org: null
  store.pariyatti.org: null
  theanarchistlibrary.org: null
  thecjbs.org: null
  thubtenchodron.org: null
  uva.theopenscholar.com: null
  wiswo.org: null
  www.108wisdom.org: null
  www.abhayagiri.org: null
  www.ajahnchah.org: null
  www.ancient-buddhist-texts.net: null
  www.are.na: null
  www.aupress.ca: null
  www.bps.lk: null
  www.buddhanet.net: null
  www.buddhistelibrary.org: null
  www.buddhistische-gesellschaft-berlin.de: null
  www.degruyter.com: null
  www.dhammatalks.org: null
  www.dhammathai.org: null
  www.dharmasite.net: null
  www.frontiersin.org: null
  www.globalbuddhism.org: null
  www.gutenberg.org: null
  www.jocbs.org: null
  www.jstor.org: null
  www.kammatthana.com: null
  www.kbrl.gov.mm: null
  www.lotsawahouse.org: null
  www.mediafire.com: null
  www.metmuseum.org: null
  www.ncbi.nlm.nih.gov: null
  www.opendemocracy.net: null
  www.researchgate.net: null
  www.scribd.com: null
  www.sheldrake.org: null
  www.shengyen.org: null
  www.shin-ibs.edu: null
  www.sirimangalo.org: null
  www.suanmokkh.org: null
  www.taylorfrancis.com: null
  www.ucpress.edu: null
  www.un.org: null
  www.watpahnanachat.org: null
  www.yorku.ca: null
  www.youtube.com: null
  www.zakstein.org: null
  youtu.be: null
  youtube.com: null
